/**
 * Email Sender Service - Gmail Integration
 * Actually sends emails generated by Ollama AI
 */

const nodemailer = require('nodemailer');
const { run, get, all } = require('../db/database');

let transporter = null;

/**
 * Initialize Gmail transporter
 */
function initEmailSender() {
  if (transporter) return transporter;

  const smtpConfig = {
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: false, // true for 465, false for other ports
    auth: {
      user: process.env.SMTP_USER || '',
      pass: process.env.SMTP_PASS || ''
    }
  };

  transporter = nodemailer.createTransport(smtpConfig);

  // Verify connection
  transporter.verify((error, success) => {
    if (error) {
      console.error('❌ Gmail connection error:', error.message);
      console.log('⚠️  Email sending disabled - check SMTP credentials');
    } else {
      console.log('✅ Gmail connected successfully - Email sending ENABLED');
    }
  });

  return transporter;
}

/**
 * Send email through Gmail
 */
async function sendEmail(emailData) {
  if (!transporter) {
    initEmailSender();
  }

  // Check if email sending is enabled
  if (process.env.ENABLE_EMAIL_SENDING !== 'true') {
    console.log('[EMAIL] Sending disabled - logging only');
    return logEmailOnly(emailData);
  }

  try {
    const mailOptions = {
      from: `"${process.env.FROM_NAME || 'SurfTrans AI'}" <${process.env.SMTP_USER || process.env.FROM_EMAIL}>`,
      to: emailData.to_email,
      subject: emailData.subject,
      html: emailData.body,
      text: emailData.body.replace(/<[^>]*>/g, ''), // Plain text fallback
      replyTo: emailData.reply_to || process.env.SMTP_USER
    };

    // Send email
    const result = await transporter.sendMail(mailOptions);
    
    console.log(`[EMAIL] ✅ Sent to ${emailData.to_email}: ${emailData.subject}`);

    // Log in database
    logEmail({
      ...emailData,
      status: 'sent',
      sent_at: new Date().toISOString(),
      message_id: result.messageId
    });

    return {
      success: true,
      messageId: result.messageId,
      sent_at: new Date().toISOString()
    };
  } catch (error) {
    console.error(`[EMAIL] ❌ Failed to send to ${emailData.to_email}:`, error.message);
    
    // Log failure
    logEmail({
      ...emailData,
      status: 'failed',
      error: error.message
    });

    return {
      success: false,
      error: error.message
    };
  }
}

/**
 * Send bulk emails (for campaigns)
 */
async function sendBulkEmails(emails) {
  const results = {
    total: emails.length,
    sent: 0,
    failed: 0,
    errors: []
  };

  // Send emails with delay to avoid spam detection
  for (const email of emails) {
    try {
      const result = await sendEmail(email);
      
      if (result.success) {
        results.sent++;
      } else {
        results.failed++;
        results.errors.push({
          to: email.to_email,
          error: result.error
        });
      }

      // Add delay between emails (1-3 seconds)
      await new Promise(resolve => 
        setTimeout(resolve, 1000 + Math.random() * 2000)
      );
    } catch (error) {
      results.failed++;
      results.errors.push({
        to: email.to_email,
        error: error.message
      });
    }
  }

  console.log(`[EMAIL BULK] Sent: ${results.sent}/${results.total}, Failed: ${results.failed}`);
  return results;
}

/**
 * Send outreach email to lead
 */
async function sendOutreachEmail(lead, emailContent) {
  return await sendEmail({
    to_email: lead.email,
    subject: emailContent.subject,
    body: emailContent.body,
    type: 'outreach',
    shipper_id: lead.id,
    ai_generated: true
  });
}

/**
 * Send follow-up email
 */
async function sendFollowUpEmail(lead, previousEmail, emailContent) {
  return await sendEmail({
    to_email: lead.email,
    subject: emailContent.subject,
    body: emailContent.body,
    type: 'follow_up',
    shipper_id: lead.id,
    ai_generated: true
  });
}

/**
 * Send quote email
 */
async function sendQuoteEmail(shipper, load, quote, emailContent) {
  return await sendEmail({
    to_email: shipper.email,
    subject: emailContent.subject,
    body: emailContent.body,
    type: 'quote',
    load_id: load.id,
    shipper_id: shipper.id,
    ai_generated: true
  });
}

/**
 * Send negotiation response
 */
async function sendNegotiationEmail(shipper, load, emailContent) {
  return await sendEmail({
    to_email: shipper.email,
    subject: emailContent.subject,
    body: emailContent.body,
    type: 'negotiation',
    load_id: load.id,
    shipper_id: shipper.id,
    ai_generated: true
  });
}

/**
 * Send confirmation email
 */
async function sendConfirmationEmail(shipper, load, emailContent) {
  return await sendEmail({
    to_email: shipper.email,
    subject: emailContent.subject,
    body: emailContent.body,
    type: 'confirmation',
    load_id: load.id,
    shipper_id: shipper.id,
    ai_generated: true
  });
}

/**
 * Log email in database
 */
function logEmail(emailData) {
  const { v4: uuidv4 } = require('uuid');
  const id = uuidv4();
  
  run(`INSERT INTO ai_emails 
       (id, load_id, shipper_id, carrier_id, from_email, to_email, subject, body, type, status, ai_generated, sent_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      id,
      emailData.load_id || null,
      emailData.shipper_id || null,
      emailData.carrier_id || null,
      emailData.from_email || process.env.SMTP_USER,
      emailData.to_email,
      emailData.subject,
      emailData.body,
      emailData.type || 'outreach',
      emailData.status || 'sent',
      emailData.ai_generated !== false ? 1 : 0,
      emailData.sent_at || new Date().toISOString()
    ]
  );
  
  return id;
}

/**
 * Log email only (without sending - for testing)
 */
function logEmailOnly(emailData) {
  const id = logEmail({
    ...emailData,
    status: 'draft'
  });
  
  console.log(`[EMAIL LOGGED] ${emailData.to_email}: ${emailData.subject}`);
  return { success: true, logged: true, id };
}

/**
 * Get email statistics
 */
function getEmailStats(days = 30) {
  return all(`
    SELECT 
      type,
      status,
      COUNT(*) as count
    FROM ai_emails
    WHERE created_at >= date('now', ?)
    GROUP BY type, status
    ORDER BY count DESC
  `, [`-${days} days`]);
}

/**
 * Get sent emails
 */
function getSentEmails(limit = 50) {
  return all(`
    SELECT e.*, s.company_name as shipper_name
    FROM ai_emails e
    LEFT JOIN shippers s ON e.shipper_id = s.id
    WHERE e.status = 'sent'
    ORDER BY e.sent_at DESC
    LIMIT ?
  `, [limit]);
}

/**
 * Track email opens (if tracking enabled)
 */
function trackEmailOpen(messageId) {
  run(`UPDATE ai_emails SET opened_at = datetime('now') WHERE message_id = ?`, [messageId]);
}

/**
 * Test Gmail connection
 */
async function testConnection() {
  try {
    if (!transporter) {
      initEmailSender();
    }
    
    await transporter.verify();
    return {
      success: true,
      message: 'Gmail connection successful',
      user: process.env.SMTP_USER
    };
  } catch (error) {
    return {
      success: false,
      message: error.message,
      setup_help: `
        1. Enable 2-Step Verification in Gmail
        2. Generate App Password: https://myaccount.google.com/apppasswords
        3. Update .env with:
           SMTP_USER=your-email@gmail.com
           SMTP_PASS=your-16-char-app-password
           ENABLE_EMAIL_SENDING=true
      `
    };
  }
}

module.exports = {
  initEmailSender,
  sendEmail,
  sendBulkEmails,
  sendOutreachEmail,
  sendFollowUpEmail,
  sendQuoteEmail,
  sendNegotiationEmail,
  sendConfirmationEmail,
  logEmail,
  getEmailStats,
  getSentEmails,
  trackEmailOpen,
  testConnection
};
